name: 'PR Automation'

on:
  pull_request:
    types: [ opened, ready_for_review ]

permissions: write-all

jobs:
  comment-job:
    name: 'Comment Job'

    runs-on: ubuntu-latest

    steps:
    - name: Create comment
      uses: actions/github-script@v7
      with:
        script: |
          const creator = context.payload.sender.login
          const opts = github.rest.issues.listForRepo.endpoint.merge({
            ...context.issue,
            creator,
            state: 'all'
          })
          const issues = await github.paginate(opts)

          for (const issue of issues) {
            if (issue.number === context.issue.number) {
              continue
            }

            if (issue.pull_request) {
              return // Creator is already a contributor.
            }
          }

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `ðŸ‘‹ Welcome!

            ì²˜ìŒ ì˜¤ì…¨êµ°ìš”!
            ì•„ì§ ìµìˆ™í•˜ì§€ ì•Šìœ¼ì‹¤í…ë°ìš”, ë¨¼ì € ì—¬ê¸° [ê°€ì´ë“œ](https://github.com/hackersground-kr/GithubWordRelay/blob/main/Policy.md)ë¥¼ í•œë²ˆ ë´ì£¼ì„¸ìš”!

            ëª¨ë¥´ëŠ”ê²Œ ìžˆìœ¼ë©´ ì–¸ì œë“  íŽ¸í•˜ê²Œ ì§ˆë¬¸í•´ì£¼ì‹œê³  ëê¹Œì§€ ìž˜ ë§ˆë¬´ë¦¬ í•´ ë³´ì•„ìš”~!`
          })

    - name: Apply assignee
      uses: actions/github-script@v7
      with:
        script: |
          const creator = context.payload.sender.login

          github.rest.issues.addAssignees({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            assignees: [ creator ]
          })

    - name: Apply labels
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['HackersGround_240406']
          })

    - name: Checkout auto-reviewer file
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github/auto_assign.yml
        sparse-checkout-cone-mode: false

    - name: Check teams
      shell: pwsh
      run: |
        # Check Modules
        if (!(Get-Module -ListAvailable -Name powershell-yaml)) {
          Install-Module powershell-yaml -Confirm:$False -Force
        }

        # Load Module
        Import-Module powershell-yaml

        [string] $reviewers = Get-Content -Path '.github/auto_assign.yml' -Raw
        $yaml = ConvertFrom-Yaml -Yaml $reviewers -AllDocuments

        [string] $reviewers = $yaml.GetEnumerator() |
          Where-Object -Property Value -Value '${{ github.actor }}' -Contains |
          Select-Object -Property Value -Unique -ExpandProperty Value |
          ? { $_.Split([Environment]::NewLine)} |
          ? { $_ -ne '${{ github.actor }}' } |
          Join-String -Separator ',' -SingleQuote

        $githubEnv = [System.Environment]::GetEnvironmentVariable('GITHUB_ENV')
        Write-Output TARGET_REVIEWERS=$reviewers >> $githubEnv
        #[System.Environment]::SetEnvironmentVariable('TARGET_REVIEWERS', $reviewers)

    - name: Request reviewers
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.pulls.requestReviewers({
            pull_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            reviewers: [ ${{ env.TARGET_REVIEWERS }} ]
          })
